### PR TITLE
versions set

### PR DESCRIPTION
**Pull request by MatthiasSachs**
version setting in project.toml is accepted by package manager. However, for the given setting the package manager sets JuLIP to v0.11.1, which seems to cause issues when compile ACEatoms.jl

There seems to be an issue with the specification of compatible ACEatoms versions in the project file of JuLIP; it seems to only allow versions of ACEatoms up 0.1.6. Thus, if JULIP is constrained to version 0.13.1. in the ACEatoms.jl project file, and ACE is set to version 0.12.5 (which requires ACEatomsv0.2.0, then no compatible version of ACEatoms is left.

### CODE REVIEW

**Comment by cortner** [comment]
fixed JuLIP Project.toml - now at least we have a set of consistent version bounds. I'll now try to get it to compile

**Comment by cortner** [comment]
I'm noticing far too many complex internals that need to be changed. I need to do this. I hope I can get it done sometime tomorrow. (cc also @davkovacs )

**Comment by cortner** [comment]
I'm sorry I can't finish it tonight - will continue tomorrow.

**Comment by davkovacs** [comment]
> I'm sorry I can't finish it tonight - will continue tomorrow.

No problem @cortner , I am travelling today to Cambridge and will come back to this tomorrow. Once you think it is ready I will create the regression tests.

**Comment by cortner** [comment]
Another cc - @zhanglw0521  - if the three of you can look at the changes I’m making in this PR it will give you a rough sense what I’ve changed in ACE.jl recently. So this PR might actually be a good place to start asking questions about internals

**Comment by cortner** [comment]
@MatthiasSachs this should now be ready for you to use. Everything except for the dipole seems to be ok now

**Comment by cortner** [comment]
@MatthiasSachs  -- from my end we could actually merge this and assign a new version and then fix the dipole codes in a second PR. But only if this is useful for you. Otherwise we better do it all at once.

**Comment by davkovacs** [comment]
For me a working version without the dipoles is already useful for the demonstration talk next week. I just have to make sure I have a couple of examples ready + I understand the basic structure of the code. The dipole stuff can wait until after next Thursday.

**Comment by cortner** [comment]
ok, then I'm tagging it now. And if either of you have any problems then we can fix the on the fly ...

**Comment by cortner** [comment]
this is now tagged as 0.0.6. 

one thing to keep in mind for your presentation, David, is that I have not prioritised performance during the rewrite from ACE1->ACE2. This will come back slowly over time, but there are several places right now where the performance is not as good as it was with ACE1.

**Pull request merged**
