### PR TITLE
Updating ACEatoms to latest ACE

### PR DESCRIPTION
**Pull request by cortner**
Latest versions of ACE are quite different and a few changes are needed in ACEatoms. This is also a test for me to see how badly I've messed up the structure of core ACE. I'll also report here what has changed if anything for usage of ACEatoms.

### CODE REVIEW

**Comment by cortner** [comment]
* @davkovacs - to generate a pair basis potential basis please use this: 
```
using ACEatoms.PairPotentials: pairbasis
maxdeg = 8; r0 = 1.0; rcut = 3.0
trans = PolyTransform(1, r0)
pB = pairbasis(:W, maxdeg, rcut, trans) 
```

**Comment by cortner** [comment]
it seems no other "user-facing" changes were required for the moment.

**Comment by cortner** [comment]
I also have a multi-threading bug, which I want to look at before merging this.

**Comment by cortner** [comment]
accidentally started pushing the embedding implementation here. This is not quite ready, needs another idea in code ACE.jl

**Comment by cortner** [comment]
@davkovacs not sure why the tests fail, it works fine for me locally. You could try this is if you want though as mentioned on slack, it is not clear to me what the better approach is for your paper...

**Comment by cortner** [comment]
there seems to be a problem version compatibility on CI but it runs ok locally

**Comment by MatthiasSachs** [comment]
Is there any chance that this PR could be merged into main? I am currently running several packages on dev branches using this version (with ACE compatibility locally changed to ACE = "<0.12.42"). However, in order set up a pull-request for `ACEbonds.jl` and make `ACEds.jl` usable for collaborators it would be helpful to have the latest version of`ACEatoms` to be compatible with at least ACE v0.12.41.

**Comment by cortner** [comment]
this is now registered as 0.0.13

**Pull request merged**
