### PR TITLE
WIP: Population dependent Species1PBasis

### PR DESCRIPTION
**Pull request by davkovacs**
I am attempting to implement a 1-particle basis which would be an `ACE.Product1pBasis`.
It would be made up of a `ACE.Scal1pBasis` which takes the value of the electronic population of the particular atom read from the `data` dictionary and a `Species1PBasis`. The population basis part should always just be P(x) = x, so the degree of that is fixed to 1. 
@cortner do you agree that this is the most sensible approach for implementing such a basis set?

### CODE REVIEW

**Comment by cortner** [comment]
this sounds a bit strange to me. Maybe we need to discuss first. Exactly what is the model you are trying to implement?

**Comment by davkovacs** [comment]
Imagine that each atom has a scalar value (the electron population) attached to them that we know from somewhere. And we just want to multiply the density by the population, so this way the one particle basis functions depend on this additional attribute, not only the geometry. 
It might seem a little pointless because the populations come from DFT so the model cannot be used on data that was not computed with DFT before, but we just want to see if the populations actually help with fitting at all. If yes we will think about obtaining them from cheap tight binding, or even doing the self consistent minimisation of the populations. This is just the first baby-step in that direction.

**Comment by cortner** [comment]
I have no problem with the population idea at all - I’m just struck by the fact that you want just a single basis function for the population. But happy to try. I’ll take a look at what you are proposing.

**Comment by davkovacs** [comment]
Thanks! I was thinking that it might be possible, just by taking a product basis made up of ZuRnYlm basis and a Scalar basis. And it will probably require a new Basis selector that chooses only the P(x)=x from the scalar basis and the normal sparse basis for the ZuRnYlm. 
But I couldn’t quite see how I could pass the population to the Scalar basis.

**Comment by davkovacs** [comment]
I think in some sense this is the 1st step in a systematic expansion. And I can totally see how this might not be enough. So ideally this new basis will have the flexibility to add higher order basis functions for the population if necessary.

**Comment by gabor1** [comment]
the point is that this *is* XPS.

**Comment by cortner** [comment]
> But I couldn’t quite see how I could pass the population to the Scalar basis

you need to specify the input symbols.

**Comment by cortner** [comment]
Having gone through the changes I don't think this comes close yet to implementing this. I'm happy to help you but let's be 100% clear about the model first. Do you mean the following: 
- each atom i has an invariant feature  x_i  associated to it. (where that comes from is irrelevant for now)
- You now want to replace the density projections
```
  sum_j    R_n(rij) Ylm(...) delta(mu - muj) 
```
with 
```
  sum_j    R_n(rij) Ylm(...) delta(mu - muj) * xj
```
correct?

**Comment by davkovacs** [comment]
I wasn’t sure if the approach I started out in this pull request is the correct one. Or whether I should use the `ACE.Prod1pBasis` to create these basis functions.

**Comment by davkovacs** [comment]
@cortner I understand that the few things I have done in the first commit are from from a finished implementation, but do you think that is the right approach to create a new `struct` or should I try to implement it as a `ACE.Prod1pBasis` ? If you can give me some pointers I would like to continue this.

**Comment by cortner** [comment]
sorry I'm so slow right now .... too many pressures. It will get better.

**Comment by cortner** [comment]
the short answer is, no I don't think this is the correct approach. I think you need to use `ACE.Prod1pBasis` to build the basis, and the new component that you need is the `Scal1pBasis`. But we need to generalise it so you can select a subset of the basis, or you need to write a wrapper that selects such a subset.

**Comment by cortner** [comment]
There is also a maybe even simpler idea. Look at the implementation of `Scal1pBasis` and copy-paste it, then modify it, so that it will always have length 1 and as its single basis function just evaluate `x`.

**Comment by cortner** [comment]
You don't necessarily need those chainrules yet (I think). They are only needed as we move towards a fully differentiable ACE code. We have some first steps, but are far from a complete solution. So most likely you can just drop those code pieces.

**Comment by cortner** [comment]
I’ll fix it in ACE.jl - ping me if you haven’t got it by tomorrow

**Comment by davkovacs** [comment]
@cortner another small comment I have is that the way I managed to specify the `OrthPolys` via the method `transformed_jacobi()` it requires to give a distance transform and a cutoff. For the case of the populations I am not quite sure how to set the cutoff (for the distance transform I just used the identity). Do you have a recommendation what you would find logical?

**Comment by cortner** [comment]
can you try the latest main branch please and see if that resolves your issue with OrthPolys?

**Comment by cortner** [comment]
@davkovacs since we need some of what I put into this PR elsewhere, I merged it into main, but I am leaving it open in case you want to do more.

**Comment by davkovacs** [comment]
Thanks a lot, I think it has everything now, if I need anything else I will just push to this branch and start a new pull request.

**Pull request merged**
