### PR TITLE
implement scaling SitePotentialBasis

### PR DESCRIPTION
**Pull request by davkovacs**
@cortner Please review,( clean-up if you would like to) and merge. I think it does the scaling correctly.

### CODE REVIEW

**Comment by cortner** [comment]
the way you assemble the vector is not robust, it can change depending on the order of the loop which is not guaranteed to remain the same. Please take a look at my suggested modification and test it.

**Comment by davkovacs** [comment]
I have implemented the missing functions, please let me know if you find it good, and we can merge it!

**Comment by cortner** [comment]
David, Please look at my final edits and confirm you don't see any problems, then I'll merge and tag first thing tomorrow morning.

**Comment by davkovacs** [comment]
It works for me! We can merge.

**Comment by cortner** [comment]
done - tagged 0.0.12.

**Pull request merged**
